### ISSUE TITLE
(Minor) Usage of JSON loads

### ISSUE THREAD

**Issue by vdksoda** [deifius/inasra#1]
In crystalyzation.py there is a line 

```python
board =json.loads(open("xwordspine.json").read())
```

Typically in Python we use a context manager when dealing with file IO so we ensure that the file object is closed on completion of the file operations (read in your case). Such as:

```python
with open('xwordspine.json', 'r') as f:
    board = json.load(f)
```
In addition you can use `json.load` which is designed to read from files.

**Comment by deifius** [comment]
I'm just now learning about context managing.  Watch out for imminent refactors!
