### ISSUE TITLE
(Discussion) Purpose of Boardtrim()

### ISSUE THREAD

**Issue by vdksoda** [deifius/inasra#2]
In crystalyzation.py the boardtrim function is as such:

```python
def boardtrim(board):
    destroy = 1
    for each in board[-1]:

        if each is ' ':
            pass
        else:
            destroy = 0
    
    if destroy == 1:
        board.pop(-1)
        boardtrim(board)
    elif destroy == 0:
        print('')
```

1. The above for loop will set `destroy=0` if there is any non empty string present. We can instead do
```python
if [element for element in board[-1] if element]:
    destroy = 0
```

Overall what is the purpose of boardtrim() ?

**Comment by deifius** [comment]
Hey there vdksoda,  boardtrim() reduces the crossword field to a minimum size needed to fit the crossword spine.  The user directed process of building the spine in wikichomp will produce a board that is big enough to accommodate the biggest possible word choice.  Then there is additional blank row/columns that boardtrim() trims off before the crystalization process begins.  This keeps the spine as the defining feature of the board.

**Comment by deifius** [comment]
I suppose that the board growing function in wikichomp could be altered to bring this process a method for wikichomp.
